### ISSUE TITLE
Someone helps me understand this

### ISSUE THREAD

**Issue by ZoltXs** [YinHangCode/homebridge-mi-philips-light#17]
I have a problem, I had homebridge in rbp3, everything configured perfect and running, I have made homebridge in Mac OsX and the same config.json copied in mac osX and problems with philips xiaomi bulbs, because the same file gives problems in different platforms? only problems with xiaomi philips bulbs, this is my error when running homebridge.

JbNoXss-Mac-mini:~ jbnoxs$ homebridge
[2018-1-29 12:45:34] Loaded plugin: homebridge-mi-aqara
[2018-1-29 12:45:34] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2018-1-29 12:45:34] ---
[2018-1-29 12:45:35] Loaded plugin: homebridge-mi-philips-light
[2018-1-29 12:45:35] Registering platform 'homebridge-mi-philips-light.MiPhilipsLightPlatform'
[2018-1-29 12:45:35] ---
[2018-1-29 12:45:37] Loaded plugin: homebridge-nefit-easy
[2018-1-29 12:45:37] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[2018-1-29 12:45:37] ---
[2018-1-29 12:45:37] Loaded config.json with 1 accessories and 2 platforms.
[2018-1-29 12:45:37] ---
[2018-1-29 12:45:37] Loading 2 platforms...
[2018-1-29 12:45:37] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]**************************************************************
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.6.8 By YinHang
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710  
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]**************************************************************
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]start success...
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]config gateways: 34ce0092452f
[2018-1-29 12:45:37] [MiAqaraPlatform] [INFO]binding to the default interface
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] Initializing MiPhilipsLightPlatform platform...
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO]********************************************************************
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO]          MiPhilipsLightPlatform v0.2.2 By YinHang
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO] GitHub: https://github.com/YinHangCode/homebridge-mi-philips-light 
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO]                                                QQ Group: 107927710 
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO]********************************************************************
[2018-1-29 12:45:37] [MiPhilipsLightPlatform] [MiPhilipsLightPlatform][INFO]start success...
/usr/local/lib/node_modules/homebridge-mi-philips-light/Devices/MiPhilipsSmartBulb.js:17
    this.device = new miio.Device({
                  ^

TypeError: miio.Device is not a constructor
    at new MiPhilipsSmartBulb (/usr/local/lib/node_modules/homebridge-mi-philips-light/Devices/MiPhilipsSmartBulb.js:17:19)
    at MiPhilipsLightPlatform.accessories (/usr/local/lib/node_modules/homebridge-mi-philips-light/index.js:87:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by ZoltXs** [comment]
I have tried this, it detects a light bulb, but it does not work.
npm install -g miio@0.14.1

**Comment by ZoltXs** [comment]
Any solution???

**Comment by YinHangCode** [comment]
···
npm remove -g miio
npm install -g miio@0.14.1
···

**Comment by ZoltXs** [comment]
before it worked, now miio 14.1 does not work, 😢😢

**Comment by ZoltXs** [comment]
some way to reset the light bulbs
